package dev.jcode.feature.marketplace

import org.json.JSONArray
import org.json.JSONObject

/**
 * Reading a `.vsix` — the format VS Code extensions ship in.
 *
 * A `.vsix` is a plain ZIP holding an `extension.vsixmanifest` and the extension itself under
 * `extension/`, whose `package.json` is the manifest that matters. JCode installs one by
 * translating that manifest into its own `extension.yaml` ([toExtensionYaml]) and unpacking the
 * `extension/` subtree as the install directory, so the extension list, detail page, uninstall and
 * developer tools all work on a VSIX without knowing a second manifest format.
 *
 * JCode implements the slice of the VS Code API that webview-based extensions use. What an
 * extension *declares* is checked here at import time ([VsixCompatibility]) because declarations are
 * reliable; what it *calls* is checked at runtime by the API shim, which throws naming the missing
 * member — a bundled extension's calls go through a renamed import (`vscode_1.window…`), so
 * scanning its code for API use would be guesswork.
 */
object VsixPackage {

    /** Where the extension's own files live inside the archive. */
    const val PAYLOAD_PREFIX = "extension/"
    private const val VSIX_MANIFEST = "extension.vsixmanifest"
    private const val PACKAGE_JSON = PAYLOAD_PREFIX + "package.json"

    /** Marker written into an install directory that came from a `.vsix`. */
    const val VSIX_MARKER = ".jcode-vsix"

    /**
     * Contribution points JCode can surface today. Anything else is reported as unsupported rather
     * than being dropped quietly, so an import says up front what will not work.
     */
    val SUPPORTED_CONTRIBUTES = setOf(
        "commands",
        "configuration",
        "configurationDefaults",
        "menus",
        "submenus",
        "views",
        "viewsContainers",
    )

    /** True when [entries] look like a `.vsix` rather than a `.jext` or some other archive. */
    fun looksLikeVsix(entries: Set<String>): Boolean =
        entries.contains(PACKAGE_JSON) && entries.any { it == VSIX_MANIFEST || it.startsWith(PAYLOAD_PREFIX) }

    /** Parse `extension/package.json`. Throws with a readable reason when the archive is not usable. */
    fun parse(packageJson: String): VsixManifest {
        val json = runCatching { JSONObject(packageJson) }
            .getOrElse { error("$PACKAGE_JSON is not valid JSON") }
        val publisher = json.optString("publisher").takeIf { it.isNotBlank() }
            ?: error("$PACKAGE_JSON has no \"publisher\"")
        val name = json.optString("name").takeIf { it.isNotBlank() }
            ?: error("$PACKAGE_JSON has no \"name\"")
        return VsixManifest(
            publisher = publisher,
            name = name,
            version = json.optString("version").takeIf { it.isNotBlank() } ?: "0.0.0",
            displayName = json.optString("displayName").takeIf { it.isNotBlank() } ?: name,
            description = json.optString("description"),
            main = json.optString("main").takeIf { it.isNotBlank() }?.removePrefix("./"),
            icon = json.optString("icon").takeIf { it.isNotBlank() }?.removePrefix("./"),
            engineRange = json.optJSONObject("engines")?.optString("vscode")?.takeIf { it.isNotBlank() },
            activationEvents = json.optJSONArray("activationEvents").toStringList(),
            contributeKeys = json.optJSONObject("contributes")?.keys()?.asSequence()?.toList().orEmpty(),
        )
    }

    /** What JCode can and cannot honour in [manifest]. */
    fun compatibilityOf(manifest: VsixManifest): VsixCompatibility {
        val supported = manifest.contributeKeys.filter { it in SUPPORTED_CONTRIBUTES }
        val unsupported = manifest.contributeKeys.filterNot { it in SUPPORTED_CONTRIBUTES }
        val warnings = buildList {
            if (manifest.main == null) {
                add("Declares no \"main\", so there is no extension code to run.")
            }
            if (unsupported.isNotEmpty()) {
                add("JCode does not implement these contribution points: ${unsupported.joinToString(", ")}.")
            }
            if (manifest.contributeKeys.none { it == "views" || it == "viewsContainers" }) {
                add("Contributes no view, so it may have no visible surface in JCode.")
            }
        }
        return VsixCompatibility(
            supportedContributes = supported,
            unsupportedContributes = unsupported,
            warnings = warnings,
        )
    }

    /**
     * The JCode manifest for [manifest]. `entry.ui` is deliberately absent: a VS Code extension has
     * no static HTML entry — its webview HTML is produced by the extension host at runtime — so the
     * view is created through the host bridge rather than by pointing at a file.
     */
    fun toExtensionYaml(manifest: VsixManifest): String = buildString {
        appendLine("# Generated by JCode from a .vsix. Edits here are lost on reinstall.")
        appendLine("id: ${manifest.id.yaml()}")
        appendLine("name: ${manifest.displayName.yaml()}")
        appendLine("publisher: ${manifest.publisher.yaml()}")
        appendLine("version: ${manifest.version.yaml()}")
        appendLine("type: app")
        appendLine("description: ${manifest.description.yaml()}")
        if (manifest.icon != null) {
            appendLine("images:")
            appendLine("  icon: ${manifest.icon.yaml()}")
        }
        appendLine("vsix:")
        appendLine("  main: ${(manifest.main ?: "").yaml()}")
        appendLine("  engine: ${(manifest.engineRange ?: "").yaml()}")
        if (manifest.activationEvents.isNotEmpty()) {
            appendLine("  activationEvents:")
            manifest.activationEvents.forEach { appendLine("    - ${it.yaml()}") }
        }
    }

    /** Quote a scalar so any punctuation in it survives the YAML round-trip. */
    private fun String.yaml(): String = "\"" + replace("\\", "\\\\").replace("\"", "\\\"")
        .replace("\n", " ").replace("\r", "") + "\""

    private fun JSONArray?.toStringList(): List<String> {
        if (this == null) return emptyList()
        return (0 until length()).mapNotNull { optString(it).takeIf { s -> s.isNotBlank() } }
    }
}

/** The parts of a VS Code `package.json` that JCode acts on. */
data class VsixManifest(
    val publisher: String,
    val name: String,
    val version: String,
    val displayName: String,
    val description: String,
    /** Entry module for the extension host, relative to the install directory. */
    val main: String?,
    /** Icon path relative to the install directory. */
    val icon: String?,
    /** The `engines.vscode` range the extension claims, recorded but not enforced. */
    val engineRange: String?,
    val activationEvents: List<String>,
    val contributeKeys: List<String>,
) {
    /** VS Code's identity for an extension, and the id JCode installs it under. */
    val id: String get() = "$publisher.$name"
}

/** What JCode can honour in a `.vsix`, reported before it is installed. */
data class VsixCompatibility(
    val supportedContributes: List<String>,
    val unsupportedContributes: List<String>,
    val warnings: List<String>,
) {
    /** True when nothing the extension declares is beyond what JCode implements. */
    val fullySupported: Boolean get() = unsupportedContributes.isEmpty() && warnings.isEmpty()
}
